"""Init

Revision ID: 4864af9dfa48
Revises: 
Create Date: 2026-03-15 13:54:49.607097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4864af9dfa48'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_email', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('leave_type', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='leavestatus'), nullable=False),
    sa.Column('manager_email', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('raw_subject', sa.String(), nullable=True),
    sa.Column('raw_body', sa.String(), nullable=True),
    sa.Column('mailhog_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mailhog_id')
    )
    op.create_index(op.f('ix_leave_requests_conversation_id'), 'leave_requests', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_department'), 'leave_requests', ['department'], unique=False)
    op.create_index(op.f('ix_leave_requests_employee_email'), 'leave_requests', ['employee_email'], unique=False)
    op.create_index(op.f('ix_leave_requests_id'), 'leave_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leave_requests_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_employee_email'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_department'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_conversation_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    # ### end Alembic commands ###
